export const huKeywords = [
  "udvarhely",
  "szekelyudvarhely",
  "pasztor",
  "istvan",
  "pásztor",
  "istván",
  "isti",
  "kreatív",
  "fejlesztő",
  "tervező",
  "web",
  "weboldal",
  "weboldalkészítés",
  "weboldaltervezés",
  "weboldalfejlesztés",
  "weboldaltervező",
  "weboldalkészítő",
  "weboldalfejlesztő",
];

export const enKeywords = [
  "creative",
  "developer",
  "designer",
  "istvan",
  "pasztor",
  "pásztor",
  "istván",
  "isti",
  "web",
  "website",
  "webdesign",
  "webdevelopment",
  "webdesigner",
  "webdeveloper",
];
