export const imageList = [
  {
    title: "Salon Manager",
    src: "/images/showcase/01.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/02.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/03.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/04.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/05.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/06.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/07.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/08.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/09.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/10.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/11.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/12.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/13.png",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/14.png",
    width: 700,
    height: 426,
  },
];
