export const imageList = [
  {
    title: "Salon Manager",
    src: "/images/showcase/01.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/02.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/03.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/04.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/05.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/06.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/07.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/08.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/09.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/10.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/11.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/12.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/13.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Salon Manager",
    src: "/images/showcase/14.webp",
    width: 700,
    height: 426,
  },
];
