export const imageList = [
  {
    title: "Salon Manager",
    src: "/images/showcase/01.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Postboard",
    src: "/images/showcase/02.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Workwear",
    src: "/images/showcase/03.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Meddison Workwear",
    src: "/images/showcase/04.webp",
    width: 700,
    height: 426,
  },
  {
    title: "NovaNoir 3D",
    src: "/images/showcase/05.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Alter Studio",
    src: "/images/showcase/06.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Alter Studio",
    src: "/images/showcase/07.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Alter Studio",
    src: "/images/showcase/08.webp",
    width: 700,
    height: 426,
  },
  {
    title: "NovaNoir Landing",
    src: "/images/showcase/09.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Wedding Manager",
    src: "/images/showcase/10.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Hargita Homes",
    src: "/images/showcase/11.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Retro Gold",
    src: "/images/showcase/12.webp",
    width: 700,
    height: 426,
  },
  {
    title: "523 Restaurant",
    src: "/images/showcase/13.webp",
    width: 700,
    height: 426,
  },
  {
    title: "Wedding Invitation",
    src: "/images/showcase/14.webp",
    width: 700,
    height: 426,
  },
];
